# Generated by Django 4.2.20 on 2025-03-23 02:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailChats',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type_option', django_mysql.models.EnumField(choices=[('Input', 'Input'), ('Output', 'Output')])),
                ('text', models.TextField()),
                ('model', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('max_token_output', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2048)])),
                ('is_string_only', models.BooleanField(default=False)),
                ('is_code_file_only', models.BooleanField(default=False)),
                ('is_multimedia_file_only', models.BooleanField(default=False)),
                ('is_musical_notes_only', models.BooleanField(default=False)),
                ('is_table_only', models.BooleanField(default=False)),
                ('include_string', models.BooleanField(default=True)),
                ('include_math_formula', models.BooleanField(default=False)),
                ('include_musical_notes', models.BooleanField(default=False)),
                ('include_code_file', models.BooleanField(default=False)),
                ('include_multimedia_file', models.BooleanField(default=False)),
                ('include_chart', models.BooleanField(default=False)),
                ('include_table', models.BooleanField(default=False)),
                ('call_name', models.CharField(blank=True, default='Default Preset', max_length=255, null=True)),
                ('what_do', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
                ('traits', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_chats', to='ollama_backend.chats')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('font_size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('show_word_count', models.BooleanField(default=False)),
                ('show_message_token_count', models.BooleanField(default=False)),
                ('show_message_token_usage', models.BooleanField(default=False)),
                ('show_model_name', models.BooleanField(default=False)),
                ('show_message_timestamp', models.BooleanField(default=False)),
                ('show_first_token_latency', models.BooleanField(default=False)),
                ('spell_check', models.BooleanField(default=False)),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ollama_backend.detailchats')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presets',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('max_token_output', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2048)])),
                ('is_string_only', models.BooleanField(default=False)),
                ('is_code_file_only', models.BooleanField(default=False)),
                ('is_multimedia_file_only', models.BooleanField(default=False)),
                ('is_musical_notes_only', models.BooleanField(default=False)),
                ('is_table_only', models.BooleanField(default=False)),
                ('include_math_formula', models.BooleanField(default=False)),
                ('include_musical_notes', models.BooleanField(default=False)),
                ('include_code_file', models.BooleanField(default=False)),
                ('include_multimedia_file', models.BooleanField(default=False)),
                ('include_chart', models.BooleanField(default=False)),
                ('include_table', models.BooleanField(default=False)),
                ('call_name', models.CharField(blank=True, default='Default Preset', max_length=255, null=True)),
                ('what_do', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
                ('apply_for_new_chat_only', models.BooleanField(default=False)),
                ('traits', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Directories',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('directory', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Chat',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='id_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ollama_backend.group_chat'),
        ),
        migrations.AddField(
            model_name='chats',
            name='id_presets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ollama_backend.presets'),
        ),
        migrations.AddField(
            model_name='chats',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
